import type { LoanRequest } from '@/types/loan';
import { LoanStage } from '@/types/loan';

export const mockLoanRequests: LoanRequest[] = [
  {
    id: 'loan-001',
    loanNumber: 'LN00001',
    customerNumber: 'CUST001',
    customerName: 'Alice Wonderland',
    customerEmail: 'alice@example.com',
    customerPhone: '555-0101',
    loanAmount: 10000,
    loanType: 'Personal Loan',
    loanPurpose: 'Home Renovation',
    currentStage: LoanStage.APPLICATION_SUBMITTED,
    submittedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    lastUpdatedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    assignedTo: 'user-jane-doe',
    documents: [
      { id: 'doc-id-1', name: 'Proof of Income', status: 'Pending' },
      { id: 'doc-id-2', name: 'Identity Verification', status: 'Pending' },
    ],
    history: [
      {
        id: 'hist-1',
        stage: LoanStage.APPLICATION_SUBMITTED,
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        userId: 'system',
        userName: 'System',
        notes: 'Loan application submitted by customer.',
      },
    ],
    stageDeadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    isOverdue: false,
  },
  {
    id: 'loan-002',
    loanNumber: 'LN00002',
    customerNumber: 'CUST002',
    customerName: 'Bob The Builder',
    customerEmail: 'bob@example.com',
    customerPhone: '555-0102',
    loanAmount: 250000,
    loanType: 'Mortgage',
    loanPurpose: 'New House Purchase',
    currentStage: LoanStage.DOCUMENT_COLLECTION,
    submittedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdatedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    documents: [
      { id: 'doc-id-3', name: 'Payslips (3 months)', status: 'Submitted' },
      { id: 'doc-id-4', name: 'Bank Statements (6 months)', status: 'Pending' },
      { id: 'doc-id-5', name: 'Property Details', status: 'Pending' },
    ],
    history: [
      {
        id: 'hist-2a',
        stage: LoanStage.APPLICATION_SUBMITTED,
        timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        userId: 'system',
        userName: 'System',
        notes: 'Loan application submitted.',
      },
      {
        id: 'hist-2b',
        stage: LoanStage.DOCUMENT_COLLECTION,
        timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        userId: 'user-john-smith',
        userName: 'John Smith',
        notes: 'Moved to document collection. Requested Payslips, Bank Statements, Property Details.',
        requiredFulfilment: 'Customer to provide Bank Statements and Property Details.',
      },
    ],
    stageDeadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
  },
  {
    id: 'loan-003',
    loanNumber: 'LN00003',
    customerNumber: 'CUST003',
    customerName: 'Charlie Brown',
    customerEmail: 'charlie@example.com',
    customerPhone: '555-0103',
    loanAmount: 5000,
    loanType: 'Auto Loan',
    loanPurpose: 'Used Car Purchase',
    currentStage: LoanStage.UNDER_REVIEW,
    submittedDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdatedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    documents: [
      { id: 'doc-id-6', name: 'Driver\'s License', status: 'Verified' },
      { id: 'doc-id-7', name: 'Vehicle Purchase Agreement', status: 'Verified' },
    ],
    history: [
      {
        id: 'hist-3',
        stage: LoanStage.UNDER_REVIEW,
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        userId: 'user-jane-doe',
        userName: 'Jane Doe',
        notes: 'All documents received. Loan is now under review.',
      },
    ],
    stageDeadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    isOverdue: true,
  },
  {
    id: 'loan-004',
    loanNumber: 'LN00004',
    customerNumber: 'CUST004',
    customerName: 'Diana Prince',
    customerEmail: 'diana@example.com',
    customerPhone: '555-0104',
    loanAmount: 150000,
    loanType: 'Business Loan',
    loanPurpose: 'Startup Capital',
    currentStage: LoanStage.APPROVED,
    submittedDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdatedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    documents: [],
    history: [],
  },
   {
    id: 'loan-005',
    loanNumber: 'LN00005',
    customerNumber: 'CUST005',
    customerName: 'Edward Nygma',
    customerEmail: 'edward@example.com',
    customerPhone: '555-0105',
    loanAmount: 2000,
    loanType: 'Personal Loan',
    loanPurpose: 'Debt Consolidation',
    currentStage: LoanStage.ADDITIONAL_INFO_REQUIRED,
    submittedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdatedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    documents: [ { id: 'doc-id-8', name: 'Proof of Address', status: 'Submitted' }],
    history: [
      {
        id: 'hist-5',
        stage: LoanStage.ADDITIONAL_INFO_REQUIRED,
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        userId: 'user-john-smith',
        userName: 'John Smith',
        notes: 'Additional income verification needed.',
        requiredFulfilment: 'Customer to provide latest tax return.',
      },
    ],
    stageDeadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
  },
];
